name: Java Runner

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Java source code"
        required: true
      input:
        description: "Program input"
        required: false

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Create Java file dynamically from browser
      - name: Create Main.java
        run: |
          printf "%s" "${{ github.event.inputs.code }}" > Main.java

      # Create stdin
      - name: Prepare input
        run: |
          printf "%s" "${{ github.event.inputs.input }}" > stdin.txt

      # Compile
      - name: Compile program
        run: |
          javac Main.java 2> compile_error.txt || true

      # If compile error -> return error
      - name: Handle compile error
        run: |
          if [ -s compile_error.txt ]; then
            cp compile_error.txt output_${{ github.run_id }}.txt
            exit 0
          fi

      # Run program
      - name: Run program
        run: |
          java Main < stdin.txt > output_${{ github.run_id }}.txt 2>&1

      # Push output so website can read it
      - name: Upload output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output_${{ github.run_id }}.txt
          git commit -m "run ${{ github.run_id }}" || echo "no change"
          git push
