name: Java Runner

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Existing Java file"
        required: false
      code:
        description: "Typed Java code"
        required: false
      input:
        description: "Program input"
        required: false

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # If browser sends custom code -> create Main.java
      - name: Create file from typed code
        if: ${{ github.event.inputs.code != '' }}
        run: |
          printf "%s" "${{ github.event.inputs.code }}" > Main.java

      # If a repo file is selected
      - name: Set filename
        run: |
          if [ "${{ github.event.inputs.filename }}" != "" ]; then
            echo "FILE=${{ github.event.inputs.filename }}" >> $GITHUB_ENV
          else
            echo "FILE=Main.java" >> $GITHUB_ENV
          fi

      # input
      - name: Prepare stdin
        run: |
          printf "%b" "${{ github.event.inputs.input }}" > stdin.txt

      # compile
      - name: Compile
        run: |
          javac "$FILE" 2> compile_error.txt || true

      # compile error handling
      - name: Handle compile error
        run: |
          if [ -s compile_error.txt ]; then
            cp compile_error.txt output_${{ github.run_id }}.txt
            exit 0
          fi

      # get classname
      - name: Detect class
        run: |
          CLASS=$(basename "$FILE" .java)
          echo "CLASS=$CLASS" >> $GITHUB_ENV

      # run
      - name: Run
        run: |
          timeout 25 java $CLASS < stdin.txt > output_${{ github.run_id }}.txt 2>&1 || echo "Program terminated" >> output_${{ github.run_id }}.txt

      # upload output
      - name: Upload output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output_${{ github.run_id }}.txt
          git commit -m "run ${{ github.run_id }}" || echo "no change"
          git push
