name: Java Runner

on:
  workflow_dispatch:
    inputs:
      filename:
        required: false
      code:
        required: false
      input:
        required: false

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create file if custom code
        if: ${{ github.event.inputs.code != '' }}
        run: |
          printf "%s" "${{ github.event.inputs.code }}" > Main.java

      - name: Select file
        run: |
          if [ "${{ github.event.inputs.filename }}" != "" ]; then
            echo "FILE=${{ github.event.inputs.filename }}" >> $GITHUB_ENV
          else
            echo "FILE=Main.java" >> $GITHUB_ENV
          fi

      - name: Prepare input
        run: |
          echo -e "${{ github.event.inputs.input }}" > stdin.txt

      - name: Compile
        run: |
          javac *.java 2> compile_error.txt || true

      - name: If compile error
        run: |
          if [ -s compile_error.txt ]; then
            cp compile_error.txt output_${{ github.run_id }}.txt
            exit 0
          fi

      - name: Detect main class
        run: |
          CLASS=$(grep -h -oP 'public\s+class\s+\K[A-Za-z0-9_]+' *.java | head -n 1)
          echo "CLASS=$CLASS" >> $GITHUB_ENV

      - name: Run program
        run: |
          touch output_${{ github.run_id }}.txt
          timeout 25 java -cp . $CLASS < stdin.txt >> output_${{ github.run_id }}.txt 2>&1 || echo "Runtime error" >> output_${{ github.run_id }}.txt

      - name: Push output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          echo "RUN:${{ github.run_id }}" >> output_${{ github.run_id }}.txt
          git add output_${{ github.run_id }}.txt
          git commit -m "run-${{ github.run_id }}"
          git push
