name: Java Console Runner

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Java file to execute"
        required: true
        type: string
      input:
        description: "Program input"
        required: false
        type: string

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create stdin
        run: |
          printf "%b" "${{ github.event.inputs.input }}" > stdin.txt

      - name: Compile Java
        run: |
          javac -encoding UTF-8 $(find . -name "*.java")

      - name: Run program
        run: |
          FILE="${{ github.event.inputs.filename }}"
          CLASS=$(basename "$FILE" .java)
          RUNID=${{ github.run_id }}

          java -cp . $CLASS < stdin.txt > output_$RUNID.txt 2>&1

      - name: Push output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output_${{ github.run_id }}.txt
          git commit -m "output ${{ github.run_id }}" || echo "no change"
          git push
