name: Run Java From Website

permissions:
  contents: write
  actions: write

on:
  repository_dispatch:
    types: [run-java]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Stop execution if no filename received
      - name: Validate filename
        run: |
          if [ -z "${{ github.event.client_payload.filename }}" ]; then
            echo "No filename provided. Exiting safely."
            exit 0
          fi

      - name: Print selected file
        run: echo "Running file: ${{ github.event.client_payload.filename }}"

      - name: Compile selected file
        run: |
          FILE="${{ github.event.client_payload.filename }}"
          javac "$FILE"

      - name: Run selected file
        run: |
          FILE="${{ github.event.client_payload.filename }}"
          CLASS=$(basename "$FILE" .java)
          java "$CLASS"
